# Generated by Django 5.0.3 on 2024-03-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideOnWay', '0004_ridedetails_cost_ridedetails_date_ridedetails_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('driverRatingId', models.AutoField(primary_key=True, serialize=False)),
                ('overallRating', models.FloatField(default=0)),
                ('totalNumberOfRides', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RideOnWay.user')),
            ],
        ),
        migrations.CreateModel(
            name='DriverReviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('passengerId', models.IntegerField()),
                ('rideId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideOnWay.user')),
            ],
        ),
    ]
