# Generated by Django 5.0.3 on 2024-03-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideOnWay', '0005_driverrating_driverreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='relatedRideId',
            field=models.IntegerField(default=None),
        ),
    ]
