# Generated by Django 5.0.3 on 2024-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
