# Generated by Django 5.0.3 on 2024-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideOnWay', '0002_ridedetails_ridesourcedestinationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedetails',
            name='passenger',
            field=models.IntegerField(null=True),
        ),
    ]
