# Generated by Django 5.0.3 on 2024-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideOnWay', '0003_alter_ridedetails_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        
        migrations.AddField(
            model_name='ridedetails',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
         migrations.AddField(
            model_name='ridedetails',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
