# Generated by Django 5.0.3 on 2024-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideOnWay', '0008_alter_driverrating_overallrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='isRideEnded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='isRideStarted',
            field=models.BooleanField(default=False),
        ),
    ]
