# This is a basic workflow to help you get started with Actions

name: RideShare

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Ride" branch
  push:
    branches: [ "Ride" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installing Dependencies
      - name: Installing Dependencies
        run: |
           sudo apt update
           sudo apt install -y python3 python3-pip python3-dev default-libmysqlclient-dev # Install Python, pip, and MySQL development headers
           python3 -m pip install --upgrade pip
           python3 -m pip install mysqlclient # Install mysqlclient
           python3 -m pip install Django # Install Django
           
      # Navigate to the directory containing manage.py
      - name: Change directory
        run: cd SoftwareEngg  # Adjust the directory path as neededSoftwareEngg
        
     

      # Run the Application
      - name: Run the Application
        run: |
           python3 manage.py runserver 0.0.0.0:8000 # Replace with the command to run your Django application
